name: Github Actions Test
run-name: test-action
on:
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: whoami
      - name: "Step2"
        run: pwd
